addString("BaseCampTent", function(){return "The inside of the tent is rather small and bare bones, just a piece of fabric to seperate you and the cold hard ground and thin canvas sheets protecting you from the elements, if barely so. You barely have enough room to sit up, and doing so makes you adopt a rather awkward position, you should probably sleep or get out soon before your back starts to hurt."})
StringMap.set("BaseCamp", "The base camp is the definition of destitute; tiny tents that barely keep out the elements, a few pathes only carved out due to constant foot traffic trampling and killing the grass, and a rather sad looking rock fire pit in the center are really all that would make you believe anyone lives here.")
addString("IntroTent", function(){return `Dark foggy thoughts, on the edge of consciousness, barely registering any sensory input. Your barely aware body even less responsive than your mind. You can barely crack your eyes open, let alone begin to sit up, suddenly it becomes very clear why, soreness and aching feelings rack you. It's more than enough discomfort to make you regret trying to come back to the waking world. You let out an unconscious groan of pain, and even that hurts. What happened to you?
<br /><br />
As you wonder how and why you ended up in this rather painful predicament. Your blurry vision focuses on the roof above you, just enough for you to make out a washed out green color and canvas like texture. Instinctually your eyes dart around the unfamiliar surrounding taking in as much as they can given how uncapacitated you are right now. Surrounded by 4 similar looking walls, you feel confident to say you're in a large tent. A luminescent blue object hangs in the middle of the tent, letting off a dim glow that slowly transitions from blue to purple and back again. It’s oddly calming and you’d probably find it in yourself to admire its beauty given different circumstances. To your side a machine seems to liven with activity, you can see a screen light up out of the corner of your vision, and a small red light fading in and out next to it. As it does so, you hear a slight pneumatic hissing and suddenly a cool sensation seems to begin in your left wrist and quickly works its way to your hands, arms, and chest. From your chest the coolness seems to circulate around your body, and in quick time the pain subsides. Your muscles still feel sore, and it's still not exactly the best you’ve felt, but it's bearable now.
<br /><br />
You take a deep breath, and slowly begin to sit up. Even at the speed your going vertigo overtakes your vision, you try to pay no mind to your body’s pleas to lie back down. Sitting up you begin to get a better visual of your surroundings. The machine’s screen has a load of symbols and graphs that you can’t make sense of. Above the screen you can see a few tubes, similar in design to a graduated cylinder, but with units and numbers that make no sense to you; Most of the tubes seem empty save for one with a dark blue grayish liquid with about half left and slowly falling. Looking around the machine to see where it would be leaking too, you see a tube about half way down pumping the liquid into your wrist. Or more accurately into a small metallic looking port of some kind on your wrist. As if that wasn’t odd enough the liquid stops draining into you and unlatches from your wrist retracting back into the machine. Before you can go to feel the metallic port or even get a good look at it, it seems to slowly fade into your {insert skin color here} skin. Only leaving what appear to be tiny barely visible dots opposite of each other where the opening was. What the…
<br /><br />
You hear the swish of the tent door flap and light floods in for a moment before it falls back in place. Looking over at the sound you see a figure in a duster coat, you would assume around 190 cm or so. The lighting is dim, but you can make out their olive colored skin, short black hair, and a rather curvy figure. “Oh hey, your finally awake, the nerd was starting to get worried.” They speak in a language that you’ve never heard, but somehow you make sense of it like instinct. You say hello back, in the same tongue she did to you. A feeling of befuddlement overcomes you and you furrow your brow. “You’re probably a bit confused and have some questions, but before I get the nerd to answer any of those, I need to know a few things about you.” She pulls a dull white chair next to the bed, not being in much of a position to tell them no, you shrug and give a nod with an affirming grunt, ready to answer whatever questions they have…`})
